### ISSUE TITLE
Integration stops working 2024.9.0

### ISSUE THREAD

**Issue by Psytoshgen** [AlexxIT/XiaomiGateway3#1434]
```
Setup failed for custom integration 'xiaomi_gateway3': Unable to import component: cannot import name 'DATA_TYPES' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.12/site-packages/zigpy/zcl/foundation.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 14, in <module>
    from .core.device import XDevice
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 9, in <module>
    from .converters import silabs
  File "/config/custom_components/xiaomi_gateway3/core/converters/silabs.py", line 4, in <module>
    from zigpy.zcl.foundation import (
ImportError: cannot import name 'DATA_TYPES' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.12/site-packages/zigpy/zcl/foundation.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 14, in <module>
    from .core.device import XDevice
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 9, in <module>
    from .converters import silabs
  File "/config/custom_components/xiaomi_gateway3/core/converters/silabs.py", line 4, in <module>
    from zigpy.zcl.foundation import (
ImportError: cannot import name 'DATA_TYPES' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.12/site-packages/zigpy/zcl/foundation.py)
```

**Comment by banalac** [comment]
Same here.

**Comment by Necroneco** [comment]
since `zigpy` replaces `DATA_TYPES` with another structure

https://github.com/zigpy/zigpy/commit/6a84984067b69435b45f0fc6f1ff22ee01a0e734

**Comment by LeandroIssa** [comment]
Same here.

**Comment by zhn9992** [comment]
日志记录器: homeassistant.setup
来源: setup.py:334
首次出现: 00:39:27 (1 次总计出现)
上次记录: 00:39:27

Setup failed for custom integration 'xiaomi_gateway3': Unable to import component: cannot import name 'DATA_TYPES' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.12/site-packages/zigpy/zcl/foundation.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 14, in <module>
    from .core.device import XDevice
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 9, in <module>
    from .converters import silabs
  File "/config/custom_components/xiaomi_gateway3/core/converters/silabs.py", line 4, in <module>
    from zigpy.zcl.foundation import (
ImportError: cannot import name 'DATA_TYPES' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.12/site-packages/zigpy/zcl/foundation.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/__init__.py", line 14, in <module>
    from .core.device import XDevice
  File "/config/custom_components/xiaomi_gateway3/core/device.py", line 9, in <module>
    from .converters import silabs
  File "/config/custom_components/xiaomi_gateway3/core/converters/silabs.py", line 4, in <module>
    from zigpy.zcl.foundation import (
ImportError: cannot import name 'DATA_TYPES' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.12/site-packages/zigpy/zcl/foundation.py)

**Comment by ErnestoBrandao** [comment]
Change the file manifest.json  /homeassistant/custom_components/xiaomi_gateway3/manifest.json to:
line 14 "zigpy>=0.52.3,<0.66.0"
for me it worked.:)

**Comment by zhn9992** [comment]
同样的问题 20240904.0

**Comment by lemeshovich** [comment]
> Change the file manifest.json /homeassistant/custom_components/xiaomi_gateway3/manifest.json to:
> line 14 "zigpy>=0.52.3,<0.66.0"

it worked for me too, thanks

**Comment by yeechen-lee** [comment]
> Change the file manifest.json /homeassistant/custom_components/xiaomi_gateway3/manifest.json to: line 14 "zigpy>=0.52.3,<0.66.0" for me it worked.:)

it worked for me too, thx

**Comment by LeandroIssa** [comment]
> Change the file manifest.json /homeassistant/custom_components/xiaomi_gateway3/manifest.json to: line 14 "zigpy>=0.52.3,<0.66.0" for me it worked.:)

it worked for me too, thx

**Comment by Algorithm0** [comment]
> Change the file manifest.json /homeassistant/custom_components/xiaomi_gateway3/manifest.json to: line 14 "zigpy>=0.52.3,<0.66.0" for me it worked.:)

If you use ZigBee configuration via another device (for example, via Sonoff USB transmission), then this "fix" will simply kill it. Don't do it.

**Comment by AlexxIT** [comment]
The correct fix has already been added to the master version

**Comment by LordArrin** [comment]
> The correct fix has already been added to the master version

Waiting for release)

**Comment by xiasi0** [comment]
修复了么？

**Comment by Algorithm0** [comment]
> The correct fix has already been added to the master version

I understand that 4.0.6 is not ready yet, but maybe it would be worth releasing a minor update so that people can update from Hacs?

**Comment by AlexxIT** [comment]
People can update from HACS at any time

**Comment by gyandor** [comment]
> Change the file manifest.json /homeassistant/custom_components/xiaomi_gateway3/manifest.json to: line 14 "zigpy>=0.52.3,<0.66.0" for me it worked.:)

Worked after reboot.

**Comment by Psytoshgen** [comment]
> s

nope, this dont work for me )

**Comment by xiasi0** [comment]
有人测试修复了么？

**Comment by 032mix** [comment]
Hi, how do we fetch the latest master through HACS? Redownloading 4.0.5 did not resolve the issue. Or is it done manually somehow?

**Comment by q1t1** [comment]
> > Change the file manifest.json /homeassistant/custom_components/xiaomi_gateway3/manifest.json to: line 14 "zigpy>=0.52.3,<0.66.0" for me it worked.:)
> 
> If you use ZigBee configuration via another device (for example, via Sonoff USB transmission), then this "fix" will simply kill it. Don't do it.

Yep, this "fix" kills ZHA and Xiaomi Aqara !

**Comment by bithajcsar** [comment]
Same here: ZHA has died...

**Comment by ValiEne** [comment]
The "fix" also killed my ZHA.

**Comment by q1t1** [comment]
> The "fix" also killed my ZHA.

And reverting the line in manifest.json don't set it back...

**Comment by bithajcsar** [comment]
Napló: homeassistant.setup
Forrás: setup.py:334
Először fordult elő: 21:27:05 (1 Események)
Utoljára naplózott: 21:27:05

Setup failed for 'zha': Unable to import component: cannot import name 'DEVICE_REGISTRY' from 'zigpy.quirks' (/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 9, in <module>
    from zha.application.gateway import Gateway
  File "/usr/local/lib/python3.12/site-packages/zha/application/gateway.py", line 14, in <module>
    from zhaquirks import setup as setup_quirks
  File "/usr/local/lib/python3.12/site-packages/zhaquirks/__init__.py", line 16, in <module>
    from zigpy.quirks import DEVICE_REGISTRY, CustomCluster, CustomDevice
ImportError: cannot import name 'DEVICE_REGISTRY' from 'zigpy.quirks' (/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 9, in <module>
    from zha.application.gateway import Gateway
  File "/usr/local/lib/python3.12/site-packages/zha/application/gateway.py", line 14, in <module>
    from zhaquirks import setup as setup_quirks
  File "/usr/local/lib/python3.12/site-packages/zhaquirks/__init__.py", line 16, in <module>
    from zigpy.quirks import DEVICE_REGISTRY, CustomCluster, CustomDevice
ImportError: cannot import name 'DEVICE_REGISTRY' from 'zigpy.quirks' (/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py)

**Comment by ValiEne** [comment]
> > The "fix" also killed my ZHA.
> 
> And reverting the line in manifest.json don't set it back...

What was the text before the "fix"?
Try a full reboot of HAOS maybe it helps

**Comment by ErnestoBrandao** [comment]
Texto before fix.:
line 14 "zigpy>=0.52.3"

:)

A quarta, 4/09/2024, 20:39, Vali Ene ***@***.***> escreveu:

**Comment by q1t1** [comment]
> > > The "fix" also killed my ZHA.
> > 
> > 
> > And reverting the line in manifest.json don't set it back...
> 
> What was the text before the "fix"? Try a full reboot of HAOS maybe it helps

I've done it, without success...

Restoring backup RN...

**Comment by 032mix** [comment]
> Hi, how do we fetch the latest master through HACS? Redownloading 4.0.5 did not resolve the issue. Or is it done manually somehow?

I just went ahead and did [the change](https://github.com/AlexxIT/XiaomiGateway3/pull/1435/files) manually then restarted HASS. It fixed it for me, but keep in mind users are reporting this is killing their ZHA setup.

**Comment by perfect-deform** [comment]
So, how to fix the "Fix" now? ZHA is broken. Reverting the 14th line doesn't help

**Comment by AlexxIT** [comment]
For fixing ZHA change `"zigpy==0.66.0"` and restart Hass.

**Comment by Nismonx** [comment]
> For fixing ZHA change `"zigpy==0.66.0"` and restart Hass.

`Logger: homeassistant.setup
Source: setup.py:334
First occurred: 21:58:50 (1 occurrences)
Last logged: 21:58:50

Setup failed for 'zha': Unable to import component: cannot import name 'DEVICE_REGISTRY' from 'zigpy.quirks' (/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 9, in <module>
    from zha.application.gateway import Gateway
  File "/usr/local/lib/python3.12/site-packages/zha/application/gateway.py", line 14, in <module>
    from zhaquirks import setup as setup_quirks
  File "/usr/local/lib/python3.12/site-packages/zhaquirks/__init__.py", line 16, in <module>
    from zigpy.quirks import DEVICE_REGISTRY, CustomCluster, CustomDevice
ImportError: cannot import name 'DEVICE_REGISTRY' from 'zigpy.quirks' (/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 9, in <module>
    from zha.application.gateway import Gateway
  File "/usr/local/lib/python3.12/site-packages/zha/application/gateway.py", line 14, in <module>
    from zhaquirks import setup as setup_quirks
  File "/usr/local/lib/python3.12/site-packages/zhaquirks/__init__.py", line 16, in <module>
    from zigpy.quirks import DEVICE_REGISTRY, CustomCluster, CustomDevice
ImportError: cannot import name 'DEVICE_REGISTRY' from 'zigpy.quirks' (/usr/local/lib/python3.12/site-packages/zigpy/quirks/__init__.py)`

**Comment by bithajcsar** [comment]
Same here. Did not fix the error.

**Comment by Nismonx** [comment]
> > For fixing ZHA change `"zigpy==0.66.0"` and restart Hass.
> 
> `Logger: homeassistant.setup Source: setup.py:334 First occurred: 21:58:50 (1 occurrences) Last logged: 21:58:50
> 
> Setup failed for 'zha': Unable to import component: cannot import name 'DEVICE_REGISTRY' from 'zigpy.quirks' (/usr/local/lib/python3.12/site-packages/zigpy/quirks/**init**.py) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component comp = await self.hass.async_add_import_executor_job( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/**init**.py", line 90, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1387, in _gcd_import File "", line 1360, in _find_and_load File "", line 1331, in _find_and_load_unlocked File "", line 935, in _load_unlocked File "", line 995, in exec_module File "", line 488, in _call_with_frames_removed File "/usr/src/homeassistant/homeassistant/components/zha/**init**.py", line 9, in from zha.application.gateway import Gateway File "/usr/local/lib/python3.12/site-packages/zha/application/gateway.py", line 14, in from zhaquirks import setup as setup_quirks File "/usr/local/lib/python3.12/site-packages/zhaquirks/**init**.py", line 16, in from zigpy.quirks import DEVICE_REGISTRY, CustomCluster, CustomDevice ImportError: cannot import name 'DEVICE_REGISTRY' from 'zigpy.quirks' (/usr/local/lib/python3.12/site-packages/zigpy/quirks/**init**.py)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component self._component_future.result() File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component comp = self._get_component() ^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/**init**.py", line 90, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1387, in _gcd_import File "", line 1360, in _find_and_load File "", line 1331, in _find_and_load_unlocked File "", line 935, in _load_unlocked File "", line 995, in exec_module File "", line 488, in _call_with_frames_removed File "/usr/src/homeassistant/homeassistant/components/zha/**init**.py", line 9, in from zha.application.gateway import Gateway File "/usr/local/lib/python3.12/site-packages/zha/application/gateway.py", line 14, in from zhaquirks import setup as setup_quirks File "/usr/local/lib/python3.12/site-packages/zhaquirks/**init**.py", line 16, in from zigpy.quirks import DEVICE_REGISTRY, CustomCluster, CustomDevice ImportError: cannot import name 'DEVICE_REGISTRY' from 'zigpy.quirks' (/usr/local/lib/python3.12/site-packages/zigpy/quirks/**init**.py)`

Wait!
let me try to complete reboot the system...

**Comment by perfect-deform** [comment]
> For fixing ZHA change `"zigpy==0.66.0"` and restart Hass.

Nope. Still the same. Even restoring from backup didn't help

**Comment by bithajcsar** [comment]
Upgrade to 4.0.6 through HACS helped!
Thanks AlexxIT!

**Comment by rama31244** [comment]
If I use zigbee2mqtt instead of ZHA, can I make the suggested change without issues?

**Comment by perfect-deform** [comment]
> For fixing ZHA change `"zigpy==0.66.0"` and restart Hass.

Worked only after rebooting system. Rebooting just HA failed. Thnx

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.6

**Comment by GeoViljoen** [comment]
> For fixing ZHA change `"zigpy==0.66.0"` and restart Hass.

Sorry if I'm being stupid, but I don't know what this means. Must I replace a file, change a value somewhere?

**Comment by AlexxIT** [comment]
If you have broken a ZHA on your own - you should know where to replace this.

**Comment by Stooovie** [comment]
BLE Mesh devices don't work with 4.0.6 and HA 2024.9
