### ISSUE TITLE
[Major] Failed to load after update HA to 2023.1.2

### ISSUE THREAD

**Issue by MaoZ1993** [AlexxIT/XiaomiGateway3#926]
Hi AlexxIT

Thanks for your great works.

I updated HA to 2023.1.2 today and this integration failed to load after reboot.

Logger: homeassistant.setup
Source: setup.py:210
First occurred: 9:33:09 PM (1 occurrences)
Last logged: 9:33:09 PM

Setup failed for custom integration xiaomi_gateway3: Unable to import component: cannot import name 'Command' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.10/site-packages/zigpy/zcl/foundation.py)

**Comment by DJTerentjev** [comment]
Update integration xiaomi_gateway3 to master or alfa version. It was fixed.

**Comment by DJTerentjev** [comment]
https://github.com/AlexxIT/XiaomiGateway3/issues/911
