### ISSUE TITLE
automation triggers broken after updating to 2021.12

### ISSUE THREAD

**Issue by rzv-trsc** [AlexxIT/XiaomiGateway3#557]
Started just after updating to 2021.12 including Core OS update:

> Source: custom_components/xiaomi_gateway3/device_trigger.py:50
> Integration: Automation (documentation, issues)
> First occurred: 3:14:56 AM (3 occurrences)
> Last logged: 3:34:42 AM
> 
> Error setting up trigger _[redacted automation name]_
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/device_automation/trigger.py", line 36, in async_attach_trigger
>     return await platform.async_attach_trigger(hass, config, action, automation_info)
>   File "/config/custom_components/xiaomi_gateway3/device_trigger.py", line 50, in async_attach_trigger
>     state_config = state_trigger.TRIGGER_SCHEMA(state_config)
> AttributeError: module 'homeassistant.components.homeassistant.triggers.state' has no attribute 'TRIGGER_SCHEMA'

Possibly related to [this](https://www.home-assistant.io/blog/2021/12/11/release-202112/#the-button-entity) ?
Was working just fine minutes before the update.
--

Gateway info:
lumi.gateway.mgl03 ZNDMWG03LM
by Xiaomi
Firmware: 1.5.0_0102

Trigger was single press on xiaomi mi wireless switch:
lumi.sensor_switch WXKG01LM
by Xiaomi
Connected via Mi Smart Home Hub
Firmware: 10

Action was 'toggle' for a couple of light domain entities.

PS/edit. While redacting the post another user beat me to it, sorry about double posting.

**Comment by AlexxIT** [comment]
Duplicate #556
