### ISSUE TITLE
Integration not loaded

### ISSUE THREAD

**Issue by Mattrees007** [AlexxIT/XiaomiGateway3#921]
Log

Logger: homeassistant.setup
Source: setup.py:210 
First occurred: 19:58:49 (1 occurrences) 
Last logged: 19:58:49

Setup failed for custom integration xiaomi_gateway3: Unable to import component: cannot import name 'Command' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.10/site-packages/zigpy/zcl/foundation.py)

**Comment by yeaaaaaahh** [comment]
I have the same issue after upgrading to Home assistant Core to 2023.1.2

**Comment by RikardzPT** [comment]
The BLE devices were restored after updating to the beta version [v3.0-alpha.1].
But now, all my zigbee devices agora not connecting to the gateway. The Mi Home app shows the same.
BLE devices ok
Zigbee devices NOK

**Comment by RikardzPT** [comment]
I downgraded from beta version [v3.0-alpha.1] to stable v2.1.2.
Full restore from before the beta, and before HA core2013.1.2.
From the gateway only had data from de BLE devices (thermometers). No zigbee devices were connected.
Exactly the same symptom on the Mi Home app. Only BLE devices available.

I checked the gateway and notice a very slow blink on the blue light. Rebooted the gateway.
All maintained the same.

I was think about re-pair a device to test but all of the sudden, I notice 1 zigbee device with online status (on Mi Home). 
Then i started to trigger them, open/close door sensor, clicking a smart switch etc and all of them re-connect and are now online on Mi Home and HA.
Somehow, either the v3.0-alpha or HA core2013.1.2... messed up the gateway and it needed to be 'shaken' :)

**Comment by peterf9** [comment]
> Log
> 
> Logger: homeassistant.setup Source: setup.py:210 First occurred: 19:58:49 (1 occurrences) Last logged: 19:58:49
> 
> Setup failed for custom integration xiaomi_gateway3: Unable to import component: cannot import name 'Command' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.10/site-packages/zigpy/zcl/foundation.py)

same thing here:

Logger: homeassistant.setup
Source: setup.py:210
First occurred: 19:58:16 (1 occurrences)
Last logged: 19:58:16

Setup failed for custom integration xiaomi_gateway3: Unable to import component: cannot import name 'Command' from 'zigpy.zcl.foundation' (/usr/local/lib/python3.10/site-packages/zigpy/zcl/foundation.py)

**Comment by AlexxIT** [comment]
#911
